apiVersion: policy.elotl.co/v1alpha1
kind: SchedulePolicy
metadata:
  name: retail-onprem-policy
spec:

  clusterSelector:
    matchLabels:
      kubernetes.io/metadata.name: "sel-nova-onprem"

  # this policy matches those resources that have this label' key value pair
  resourceSelectors:
    labelSelectors:
    - matchLabels:
        retail-store-sample: onprem

  # this policy matches all resources that have the key listed below 
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: Exists

  # K8s resources will be grouped by this label key i.e. those with the same "value" for this key will be 
  # placed together in a single k8s workload cluster 
  # TODO is grouping really needed when we spread-duplicate resources?
  groupBy:
    labelKey: retail-store-sample
