apiVersion: policy.elotl.co/v1alpha1
kind: SchedulePolicy
metadata:
  name: retail-spill-policy
spec:

  orderedClusterSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values: [sel-nova-onprem, sel-nova-cloud]

  # this policy matches those resources that have this label' key value pair
  resourceSelectors:
    labelSelectors:
    - matchLabels:
        retail-store-sample: spill

  # this policy matches all resources that have the key listed below 
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: Exists

  # K8s resources will be grouped by this label key i.e. those with the same "value" for this key will be 
  # placed together in a single k8s workload cluster 
  # TODO is grouping really needed when we spread-duplicate resources?
  groupBy:
    labelKey: retail-store-sample
